# Generated by Django 4.1.1 on 2022-09-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='is_pablished',
            new_name='is_published',
        ),
    ]
